name: ESLint Check

on: [workflow_dispatch, push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.18

      - name: Install dependencies
        run: bun install

      - name: Run Lint
        run: bun run eslint . --no-fix
